resolver:    lts-17.5

packages:
- .

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  ab7a4c19a882168c3038b10d3ba4020a24595bda

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  1d5fb05157fd308278e19d048e56068e96f17d76

- bioinformatics-toolkit-0.8.0
- clustering-0.4.1
- HsHTSLib-1.9.2
- jmacro-0.6.16
- bbi-0.1.1
